In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("cust_satisfaction.csv")

In [3]:
df

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,Male,Loyal Customer,Personal Travel,Eco Plus,neutral or dissatisfied,13,460,5,4,5,25,18.0
1,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,25,235,1,3,1,1,6.0
2,Female,Loyal Customer,Business travel,Business,satisfied,26,1142,5,4,5,0,0.0
3,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied,25,562,2,3,2,11,9.0
4,Male,Loyal Customer,Business travel,Business,satisfied,61,214,3,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103899,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,23,192,2,4,2,3,0.0
103900,Male,Loyal Customer,Business travel,Business,satisfied,49,2347,5,5,4,0,0.0
103901,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,30,1995,4,4,4,7,14.0
103902,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,22,1000,1,1,1,0,0.0
103903,Male,Loyal Customer,Business travel,Business,neutral or dissatisfied,27,1723,1,4,1,0,0.0

In [4]:
df.columns

Index(['Gender', 'Customer Type', 'Type of Travel', 'Class', 'satisfaction',
       'Age', 'Flight Distance', 'Inflight entertainment', 'Baggage handling',
       'Cleanliness', 'Departure Delay in Minutes',
       'Arrival Delay in Minutes'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103904 entries, 0 to 103903
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Gender                      103904 non-null  str
 1   Customer Type               103904 non-null  str
 2   Type of Travel              103904 non-null  str
 3   Class                       103904 non-null  str
 4   satisfaction                103904 non-null  str
 5   Age                         103904 non-null  int64
 6   Flight Distance             103904 non-null  int64
 7   Inflight entertainment      103904 non-null  int64
 8   Baggage handling            103904 non-null  int64
 9   Cleanliness                 103904 non-null  int64
 10  Departure Delay in Minutes  103904 non-null  int64
 11  Arrival Delay in Minutes    103594 non-null  float64
dtypes: float64(1), int64(6), str(5)
memory usage: 9.5 MB

In [6]:
df.duplicated().sum()

np.int64(172)

In [7]:
df.drop_duplicates(inplace=True)

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.isna().sum()

Gender                          0
Customer Type                   0
Type of Travel                  0
Class                           0
satisfaction                    0
Age                             0
Flight Distance                 0
Inflight entertainment          0
Baggage handling                0
Cleanliness                     0
Departure Delay in Minutes      0
Arrival Delay in Minutes      310
dtype: int64

In [10]:
df.dropna(inplace=True)

In [11]:
df.isna().sum()

Gender                        0
Customer Type                 0
Type of Travel                0
Class                         0
satisfaction                  0
Age                           0
Flight Distance               0
Inflight entertainment        0
Baggage handling              0
Cleanliness                   0
Departure Delay in Minutes    0
Arrival Delay in Minutes      0
dtype: int64

In [12]:
df.info()

<class 'pandas.DataFrame'>
Index: 103422 entries, 0 to 103903
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Gender                      103422 non-null  str
 1   Customer Type               103422 non-null  str
 2   Type of Travel              103422 non-null  str
 3   Class                       103422 non-null  str
 4   satisfaction                103422 non-null  str
 5   Age                         103422 non-null  int64
 6   Flight Distance             103422 non-null  int64
 7   Inflight entertainment      103422 non-null  int64
 8   Baggage handling            103422 non-null  int64
 9   Cleanliness                 103422 non-null  int64
 10  Departure Delay in Minutes  103422 non-null  int64
 11  Arrival Delay in Minutes    103422 non-null  float64
dtypes: float64(1), int64(6), str(5)
memory usage: 10.3 MB

In [13]:
df['Gender'].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [14]:
Gender_dict = {'Male':1, 'Female':2}

In [15]:
df['Gender'] = df['Gender'].map(Gender_dict)

In [16]:
df

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,1,Loyal Customer,Personal Travel,Eco Plus,neutral or dissatisfied,13,460,5,4,5,25,18.0
1,1,disloyal Customer,Business travel,Business,neutral or dissatisfied,25,235,1,3,1,1,6.0
2,2,Loyal Customer,Business travel,Business,satisfied,26,1142,5,4,5,0,0.0
3,2,Loyal Customer,Business travel,Business,neutral or dissatisfied,25,562,2,3,2,11,9.0
4,1,Loyal Customer,Business travel,Business,satisfied,61,214,3,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103899,2,disloyal Customer,Business travel,Eco,neutral or dissatisfied,23,192,2,4,2,3,0.0
103900,1,Loyal Customer,Business travel,Business,satisfied,49,2347,5,5,4,0,0.0
103901,1,disloyal Customer,Business travel,Business,neutral or dissatisfied,30,1995,4,4,4,7,14.0
103902,2,disloyal Customer,Business travel,Eco,neutral or dissatisfied,22,1000,1,1,1,0,0.0
103903,1,Loyal Customer,Business travel,Business,neutral or dissatisfied,27,1723,1,4,1,0,0.0

In [17]:
df.info()

<class 'pandas.DataFrame'>
Index: 103422 entries, 0 to 103903
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Gender                      103422 non-null  int64
 1   Customer Type               103422 non-null  str
 2   Type of Travel              103422 non-null  str
 3   Class                       103422 non-null  str
 4   satisfaction                103422 non-null  str
 5   Age                         103422 non-null  int64
 6   Flight Distance             103422 non-null  int64
 7   Inflight entertainment      103422 non-null  int64
 8   Baggage handling            103422 non-null  int64
 9   Cleanliness                 103422 non-null  int64
 10  Departure Delay in Minutes  103422 non-null  int64
 11  Arrival Delay in Minutes    103422 non-null  float64
dtypes: float64(1), int64(7), str(4)
memory usage: 10.3 MB

In [18]:
df['Customer Type'].unique()

<StringArray>
['Loyal Customer', 'disloyal Customer']
Length: 2, dtype: str

In [19]:
Customer_Type_dict = {'Loyal Customer':1,'disloyal Customer':2}

In [20]:
# df['Customer Type'] = df['Customer Type'].map(Customer_Type_dict)

In [21]:
df['Type of Travel'].unique()

<StringArray>
['Personal Travel', 'Business travel']
Length: 2, dtype: str

In [22]:
Type_of_Travel_dict = {'Personal Travel':1, 'Business travel':2}

In [23]:
# df['Type of Travel'] = df['Type of Travel'].map(Type_of_Travel_dict)

In [24]:
df['Class'].unique()

<StringArray>
['Eco Plus', 'Business', 'Eco']
Length: 3, dtype: str

In [25]:
Class_dict = {'Eco Plus':1, 'Business':2, 'Eco':3}

In [26]:
# df['Class'] = df['Class'].map(Class_dict)

In [27]:
df['satisfaction'].unique()

<StringArray>
['neutral or dissatisfied', 'satisfied']
Length: 2, dtype: str

In [28]:
satisfaction_dict = {'neutral or dissatisfied':1, 'satisfied':2}

In [29]:
# df['satisfaction'] = df['satisfaction'].map(satisfaction_dict)

In [30]:
df.info()

<class 'pandas.DataFrame'>
Index: 103422 entries, 0 to 103903
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Gender                      103422 non-null  int64
 1   Customer Type               103422 non-null  str
 2   Type of Travel              103422 non-null  str
 3   Class                       103422 non-null  str
 4   satisfaction                103422 non-null  str
 5   Age                         103422 non-null  int64
 6   Flight Distance             103422 non-null  int64
 7   Inflight entertainment      103422 non-null  int64
 8   Baggage handling            103422 non-null  int64
 9   Cleanliness                 103422 non-null  int64
 10  Departure Delay in Minutes  103422 non-null  int64
 11  Arrival Delay in Minutes    103422 non-null  float64
dtypes: float64(1), int64(7), str(4)
memory usage: 10.3 MB

In [31]:
df

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,1,Loyal Customer,Personal Travel,Eco Plus,neutral or dissatisfied,13,460,5,4,5,25,18.0
1,1,disloyal Customer,Business travel,Business,neutral or dissatisfied,25,235,1,3,1,1,6.0
2,2,Loyal Customer,Business travel,Business,satisfied,26,1142,5,4,5,0,0.0
3,2,Loyal Customer,Business travel,Business,neutral or dissatisfied,25,562,2,3,2,11,9.0
4,1,Loyal Customer,Business travel,Business,satisfied,61,214,3,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103899,2,disloyal Customer,Business travel,Eco,neutral or dissatisfied,23,192,2,4,2,3,0.0
103900,1,Loyal Customer,Business travel,Business,satisfied,49,2347,5,5,4,0,0.0
103901,1,disloyal Customer,Business travel,Business,neutral or dissatisfied,30,1995,4,4,4,7,14.0
103902,2,disloyal Customer,Business travel,Eco,neutral or dissatisfied,22,1000,1,1,1,0,0.0
103903,1,Loyal Customer,Business travel,Business,neutral or dissatisfied,27,1723,1,4,1,0,0.0

In [32]:
df.drop(['Gender','Customer Type'], axis=1 ,inplace = True)

In [33]:
df

,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,Personal Travel,Eco Plus,neutral or dissatisfied,13,460,5,4,5,25,18.0
1,Business travel,Business,neutral or dissatisfied,25,235,1,3,1,1,6.0
2,Business travel,Business,satisfied,26,1142,5,4,5,0,0.0
3,Business travel,Business,neutral or dissatisfied,25,562,2,3,2,11,9.0
4,Business travel,Business,satisfied,61,214,3,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...
103899,Business travel,Eco,neutral or dissatisfied,23,192,2,4,2,3,0.0
103900,Business travel,Business,satisfied,49,2347,5,5,4,0,0.0
103901,Business travel,Business,neutral or dissatisfied,30,1995,4,4,4,7,14.0
103902,Business travel,Eco,neutral or dissatisfied,22,1000,1,1,1,0,0.0
103903,Business travel,Business,neutral or dissatisfied,27,1723,1,4,1,0,0.0