In [52]:
import pandas as pd
# dup > null > str>num >drop
# df.find(domain, localedir=None, languages=None, all=False)

In [53]:
df = pd.read_csv('Used_Bikes.csv')

In [54]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [55]:
df.duplicated().sum()

np.int64(25324)

In [56]:
df['bike_name'].duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
32643     True
32644     True
32645     True
32646     True
32647     True
Name: bike_name, Length: 32648, dtype: bool

In [57]:
df.drop_duplicates(inplace= True)

In [58]:
df.duplicated().sum()

np.int64(0)

In [59]:
df['bike_name'].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
9362    False
9369    False
9370    False
9371    False
9372    False
Name: bike_name, Length: 7324, dtype: bool

In [60]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [61]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   str
 1   price       7324 non-null   float64
 2   city        7324 non-null   str
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   str
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   str
dtypes: float64(4), str(4)
memory usage: 515.0 KB

In [62]:
df['bike_name'].unique()

<StringArray>
[      'TVS Star City Plus Dual Tone 110cc',
              'Royal Enfield Classic 350cc',
                     'Triumph Daytona 675R',
                     'TVS Apache RTR 180cc',
     'Yamaha FZ S V 2.0 150cc-Ltd. Edition',
                         'Yamaha FZs 150cc',
            'Honda CB Hornet 160R  ABS DLX',
      'Hero Splendor Plus Self Alloy 100cc',
        'Royal Enfield Thunderbird X 350cc',
 'Royal Enfield Classic Desert Storm 500cc',
 ...
                 'Bajaj Discover150S 150cc',
                       'Hero i Smart 125cc',
               'Hero Splendor Plus  100 cc',
                'Hero Splendor Plus 100 CC',
                      'Hero Karizma 223 cc',
                         'TVS MAX 4R 110cc',
                   'Mahindra Pantero 110cc',
                      'Hero Ambition 135cc',
                'Honda CBR 250R Repsol ABS',
                'Hero Hunk Rear Disc 150cc']
Length: 471, dtype: str

In [63]:
bike_name_dict = {
    'TVS Star City Plus Dual Tone 110cc':1,
              'Royal Enfield Classic 350cc':2,
                     'Triumph Daytona 675R':3,
                     'TVS Apache RTR 180cc':4,
     'Yamaha FZ S V 2.0 150cc-Ltd. Edition':5,
                         'Yamaha FZs 150cc':6,
            'Honda CB Hornet 160R  ABS DLX':7,
      'Hero Splendor Plus Self Alloy 100cc':8,
        'Royal Enfield Thunderbird X 350cc':9,
 'Royal Enfield Classic Desert Storm 500cc':10,
                 'Bajaj Discover150S 150cc':11,
                       'Hero i Smart 125cc':12,
               'Hero Splendor Plus  100 cc':13,
                'Hero Splendor Plus 100 CC':14,
                      'Hero Karizma 223 cc':15,
                         'TVS MAX 4R 110cc':16,
                   'Mahindra Pantero 110cc':17,
                      'Hero Ambition 135cc':18,
                'Honda CBR 250R Repsol ABS':19,
                'Hero Hunk Rear Disc 150cc':20
}

In [64]:
df["bike_name"] = df["bike_name"].map(bike_name_dict)

In [65]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   594 non-null    float64
 1   price       7324 non-null   float64
 2   city        7324 non-null   str
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   str
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   str
dtypes: float64(5), str(3)
memory usage: 515.0 KB

In [66]:
df['city'].unique()

<StringArray>
[   'Ahmedabad',        'Delhi',    'Bangalore',       'Mumbai',
       'Kalyan',    'Faridabad',       'Mettur',    'Hyderabad',
      'Kaithal',      'Gurgaon',
 ...
  'Bhubaneswar',      'Raiganj', 'Bhilai Nagar',       'Baloda',
     'Anantnag',   'Berhampore',      'Silvasa',       'Hospet',
        'Palai',        'Sidhi']
Length: 443, dtype: str

In [67]:
city_dict = {'Ahmedabad':1,          'Delhi':2,        'Bangalore':3 ,         'Mumbai':4,
             'Kalyan' : 5,           'Faridabad':6,    'Mettur' : 7  ,         'Hyderabad' : 8,
             'Kaithal': 9 ,          'Gurgaon' : 10 ,  'Bhubaneswar' : 11,     'Raiganj' : 12 , 
             'Bhilai Nagar':13,      'Baloda':14,      'Anantnag':15 ,         'Berhampore':16,    
             'Silvasa':17 ,          'Hospet':18,      'Palai':19,             'Sidhi':20 }

In [68]:
df["city"] = df['city'].map(city_dict)

In [69]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   594 non-null    float64
 1   price       7324 non-null   float64
 2   city        4165 non-null   float64
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   str
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   str
dtypes: float64(6), str(2)
memory usage: 515.0 KB

In [70]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [71]:
owner_dict = {
    'First Owner':1, 'Second Owner':2, 'Third Owner':3, 'Fourth Owner Or More':4
}

In [72]:
df['owner'] = df["owner"].map(owner_dict)

In [73]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   594 non-null    float64
 1   price       7324 non-null   float64
 2   city        4165 non-null   float64
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   int64
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   str
dtypes: float64(6), int64(1), str(1)
memory usage: 515.0 KB

In [74]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [75]:
brand_dict = {'TVS':1,         'Royal Enfield':2,      'Triumph':3,             'Yamaha':4,
              'Honda':5,       'Hero':6,               'Bajaj':7,               'Suzuki':8,
              'Benelli':9,     'KTM':10,               'Mahindra':11,           'Kawasaki':12,
              'Ducati':13,     'Hyosung':14 ,          'Harley-Davidson':15,    'Jawa':16,
              'BMW':17,        'Indian':18,            'Rajdoot':19,            'LML':20,
              'Yezdi':21,      'MV':22,                'Ideal':23}

In [76]:
df["brand"] = df["brand"].map(brand_dict)

In [77]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   594 non-null    float64
 1   price       7324 non-null   float64
 2   city        4165 non-null   float64
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   int64
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   int64
dtypes: float64(6), int64(2)
memory usage: 515.0 KB

In [78]:
df.dropna(inplace=True)

In [79]:
df

      bike_name     price  city  kms_driven  owner   age  power  brand
0           1.0   35000.0   1.0     17654.0      1   3.0  110.0      1
1           2.0  119900.0   2.0     11000.0      1   4.0  350.0      2
2           3.0  600000.0   2.0       110.0      1   8.0  675.0      3
3           4.0   65000.0   3.0     16329.0      1   4.0  180.0      1
4           5.0   80000.0   3.0     10000.0      1   3.0  150.0      4
...         ...       ...   ...         ...    ...   ...    ...    ...
9205        6.0   31000.0   2.0     58000.0      1  10.0  150.0      4
9235        2.0  150000.0   3.0      5400.0      1   8.0  350.0      2
9241       10.0  140000.0   2.0      8500.0      1   5.0  500.0      2
9245        2.0  105000.0   2.0     14779.0      1   4.0  350.0      2
9362       20.0   25000.0   2.0     48587.0      1   8.0  150.0      6

[369 rows x 8 columns]

In [80]:
df.info()

<class 'pandas.DataFrame'>
Index: 369 entries, 0 to 9362
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   369 non-null    float64
 1   price       369 non-null    float64
 2   city        369 non-null    float64
 3   kms_driven  369 non-null    float64
 4   owner       369 non-null    int64
 5   age         369 non-null    float64
 6   power       369 non-null    float64
 7   brand       369 non-null    int64
dtypes: float64(6), int64(2)
memory usage: 25.9 KB

In [81]:
df.drop(['city', 'owner'],axis=1,inplace = True)